version: '3'

volumes:
  storage-data: 
  mysql-data:
    name: ${PROJECT_NAME}-data

networks:
  network-id:
    name: ${PROJECT_NAME}-network

services:
  mysql:
    build:
      context: ./docker/mysql
      args:
        mysql_version: ${MYSQL_VERSION}
    container_name: ${PROJECT_NAME}-mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - network-id

  php-fpm:
    image: jkaninda/laravel-php-fpm:${PHP_VERSION}
    build:
      context: ./docker/php
      args:
        php_version: ${PHP_VERSION}
    container_name: php-fpm
    restart: unless-stopped    
    volumes:
      - ./www:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - mysql
    networks:
      - network-id
    environment:
        - APP_ENV=production
  nginx-server:
     image: jkaninda/nginx-fpm:alpine
     container_name: nginx-server
     restart: unless-stopped
     ports:
      - 80:80
     volumes:
      - ./www:/var/www/html
     environment:
       - DOCUMENT_ROOT=/var/www/html/public
       - CLIENT_MAX_BODY_SIZE=20M
       - PHP_FPM_HOST=php-fpm:9000 
     networks:
      - network-id
     links:
      - mysql