version: '3'
networks:
  network-id:
    driver: bridge

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        php_version: ${PHP_VERSION}
    container_name: ${PROJECT_NAME}-php
    volumes:
      - ./www:/var/www/app
    expose:
      - "9000"
    networks:
      - network-id
    environment:
      - APP_DEBUG = ${APP_DEBUG}
      - APP_ENV = ${APP_ENV}
      - APP_FAKER_LOCALE = ${APP_FAKER_LOCALE}
      - APP_FALLBACK_LOCALE = ${APP_FALLBACK_LOCALE}
      - APP_FALLBACK_TIMEZONE = ${APP_FALLBACK_TIMEZONE}
      - APP_KEY = ${APP_KEY}
      - APP_LOCALE = ${APP_LOCALE}
      - APP_NAME = ${APP_NAME}
      - APP_TIMEZONE = ${APP_TIMEZONE}
      - DB_CONNECTION = ${DB_CONNECTION}
      - DB_DATABASE = ${DB_DATABASE}
      - DB_HOST = ${DB_HOST}
      - DB_PASSWORD = ${DB_PASSWORD}
      - DB_PORT = ${DB_PORT}
      - DB_USERNAME = ${DB_USERNAME}
      - BCRYPT_ROUNDS = ${BCRYPT_ROUNDS}
      - BROADCAST_CONNECTION = ${BROADCAST_CONNECTION}
      - CACHE_STORE = ${CACHE_STORE}
      - FILESYSTEM_DISK = ${FILESYSTEM_DISK}
      - LOG_CHANNEL = ${LOG_CHANNEL}
      - LOG_LEVEL = ${LOG_LEVEL}
      - LOG_STACK = ${LOG_STACK}
      - MAIL_FROM_ADDRESS = ${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME = ${MAIL_FROM_NAME}
      - MAIL_HOST = ${MAIL_HOST}
      - MAIL_MAILER = ${MAIL_MAILER}
      - MAIL_PORT = ${MAIL_PORT}
      - MEMCACHED_HOST = ${MEMCACHED_HOST}
      - MYSQL_VERSION = ${MYSQL_VERSION}
      - PHP_PORT = ${PHP_PORT}
      - PHP_VERSION = ${PHP_VERSION}
      - PROJECT_NAME = ${PROJECT_NAME}
      - QUEUE_CONNECTION = ${QUEUE_CONNECTION}
      - REDIS_CLIENT = ${REDIS_CLIENT}
      - REDIS_HOST = ${REDIS_HOST}
      - REDIS_PORT  = ${REDIS_PORT}
      - SESSION_DRIVER = ${SESSION_DRIVER}
      - SESSION_ENCRYPT = ${SESSION_ENCRYPT}
      - SESSION_LIFETIME = ${SESSION_LIFETIME}
      - SESSION_PATH = ${SESSION_PATH}
      - VITE_APP_NAME = ${VITE_APP_NAME}
      - COMPOSER_ALLOW_SUPERUSER = ${COMPOSER_ALLOW_SUPERUSER}
      - VITE_HOSTAPI = ${VITE_HOSTAPI}

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/app
    depends_on:
      - php
    networks:
      - network-id