version: '3'

volumes:
  mysql-data:
    name: ${PROJECT_NAME}-data

networks:
  network-id:
    driver: bridge

services:
  mysql:
    build:
      context: ./docker/mysql
      args:
        mysql_version: ${MYSQL_VERSION}
    container_name: database
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    expose:
      - "3306"
    restart: always
    networks:
      - network-id

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        php_version: ${PHP_VERSION}
    container_name: ${PROJECT_NAME}-php
    expose:
      - "9000"
    volumes:
      - ./www:/var/www/app
    networks:
      - network-id
    depends_on:
      - mysql
    entrypoint: ["/usr/bin/entrypoint.sh"]

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "7000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/app:delegated
    depends_on:
      - php
      - mysql
    networks:
      - network-id
